# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

services:
  escolaapi:
    image: escolaapi
    build:
      context: .
      dockerfile: Escola.API/Dockerfile
    ports:
      - 5160:5160
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=User ID=postgres;Password=${DB_PASSWORD};Host=host.docker.internal;Port=5432;Database=Escola;Pooling=true;Connection Lifetime=0;