<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Escola.Domain\Escola.Domain.csproj" />
    <ProjectReference Include="..\Escola.Application\Escola.Application.csproj" />
    <ProjectReference Include="..\Escola.Infra.Data\Escola.Infra.Data.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
